language: 
  - r
  - java
cache: packages
env:
  global:
    - MONGODB_VERSION=3.2.8

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - wget http://www.apache.org/dyn/closer.lua/spark/spark-1.6.2/spark-1.6.2.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar -xzf spark-1.6.2.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 15
  - mongo clean.js
  - bash import.sh
  - mongo request.js
  - bash export.sh

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"))'
script:
  - Rscript graph.R
