services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
before_script:
  - sleep 15
  - mongo clean.js
  - bash import.sh
  - mongo request.js