language: 
  - r
  - java

jdk:
  - oraclejdk8

cache: 
  - packages
  - deps
env:
  global:
    - MONGODB_VERSION=3.2.8

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - wget http://d3kbcqa49mib13.cloudfront.net/spark-1.6.2-bin-hadoop2.6.tgz
  - wget https://oss.sonatype.org/content/repositories/releases/org/mongodb/mongodb-driver/3.3.0/mongodb-driver-3.3.0.jar
  - wget http://search.maven.org/remotecontent?filepath=org/mongodb/mongo-hadoop/mongo-hadoop-core/1.5.2/mongo-hadoop-core-1.5.2.jar -O mongo-hadoop-core-1.5.2.jar
  - wget https://oss.sonatype.org/content/repositories/releases/org/mongodb/mongo-java-driver/3.3.0/mongo-java-driver-3.3.0.jar
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar -xzf spark-1.6.2-bin-hadoop2.6.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db & > allout.txt 2>&1
  - sleep 15
  - mongo clean.js >> allout.txt 2>&1
  - bash import.sh >> allout.txt 2>&1
  - mongo request.js >> allout.txt 2>&1
  - bash export.sh >> allout.txt 2>&1
  - cd deps;mvn -q install  
  - cd .. 

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"))'  >> allout.txt 2>&1
script:
  - Rscript graph.R  >> allout.txt 2>&1
  - bash sparko.sh  >> allout.txt 2>&1
