 mongoimport --db cordir --collection project --file "data/cordis-fp7projects.csv.mongo" --type csv --headerline
 mongoimport --db cordir --collection organization --file "data/cordis-fp7organizations.csv.mongo" --type csv --headerline
 mongoimport --db cordir --collection brief --file "data/cordis-fp7briefs.csv.mongo" --type csv --headerline
 mongoimport --db cordir --collection country --file "data/cordisref-countries.csv.mongo" --type csv --headerline
 mongoimport --db cordir --collection fundingScheme --file "data/cordisref-projectFundingSchemeCategory.csv.mongo" --type csv --headerline
 mongoimport --db cordir --collection activityType --file "data/cordisref-organizationActivityType.csv.mongo" --type csv --headerline
 mongoimport --db cordir --collection programme --file "data/cordisref-FP7programmes.csv.mongo" --type csv --headerline
 mongoimport --db cordir --collection sicCode --file "data/cordisref-sicCode.csv.mongo" --type csv --headerline
 mongoimport --db cordir --collection subjects --file "data/subjects.csv" --type csv --headerline
