 mongoimport --db cordis --collection project --file "data/cordis-fp7projects.csv.mongo" --type csv --headerline
 mongoimport --db cordis --collection organization --file "data/cordis-fp7organizations.csv.mongo" --type csv --headerline
 mongoimport --db cordis --collection brief --file "data/cordis-fp7briefs.csv.mongo" --type csv --headerline
 mongoimport --db cordis --collection country --file "data/cordisref-countries.csv.mongo" --type csv --headerline
 mongoimport --db cordis --collection fundingScheme --file "data/cordisref-projectFundingSchemeCategory.csv.mongo" --type csv --headerline
 mongoimport --db cordis --collection activityType --file "data/cordisref-organizationActivityType.csv.mongo" --type csv --headerline
 mongoimport --db cordis --collection programme --file "data/cordisref-FP7programmes.csv.mongo" --type csv --headerline
 mongoimport --db cordis --collection sicCode --file "data/cordisref-sicCode.csv.mongo" --type csv --headerline
 mongoimport --db cordis --collection subjects --file "data/subjects.csv" --type csv --headerline
